export const LANDING = "/";
export const SIGN_UP="/signup";
export const SIGN_IN="/signin";
export const HOME ="/signup";
export const DASHBOARD ='/dashboard';
export const VOUCHER ='/voucher';
export const TABLE ='/table';
export const ADMIN ="/Admin";
 export const BULK ='/Bulk';
export const STANDALONE = '/Standalone';
 export const PASSWORD_FORGET ="/forget_password";
 export const CHANGE_PASSWORD="/Change_password"
 export const UPDATE="/Update";
 export const NOTFOUND="/404"
